name: Run Tests

on:
  workflow_call:

jobs:
  test:
    name: Run all tests (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          rust-version: 1.90.0
          install-mise: 'true'
          mise-tools: just

      - name: Run all tests
        run: mise exec -- just test
        env:
          RUST_TEST_THREADS: 1
